### ISSUE TITLE
Fix task popup in map

### ISSUE THREAD

**Issue by verfehlix** [verfehlix/GeoTasks#10]
In the task detail popup, please include:
- location name
- location adress
- button to navigate to task detail (or make the whole thing clickable)

also, the width of the box seems to be acting wierd:
Sometimes, its small/ok :
![1](https://cloud.githubusercontent.com/assets/7032914/14678473/14f24fa4-0716-11e6-85e7-03a8a5d74294.PNG)

Sometimes, its as large as the screen, even if the title is shorter:
![2](https://cloud.githubusercontent.com/assets/7032914/14678474/1506c308-0716-11e6-9733-55ccd8679eae.PNG)

**Comment by StefanHelmstetter** [comment]
The popup includes everything mentioned, but the width is somehow set by the default functionality of this popup. I need to have a look how to adapt it manually.

**Comment by StefanHelmstetter** [comment]
ClickListener added. Needs to be implemented. We may need a function to get a Task from title and location.
