### ISSUE TITLE
Review UI Sketches

### ISSUE THREAD

**Issue by verfehlix** [verfehlix/GeoTasks#4]
@StefanHelmstetter @fabianstz @BlackIHawk,

bitte schaut euch mal kurz die UI Sketches an für die ersten Zwei Activites:

[https://github.com/verfehlix/GeoTasks/wiki/UI-Sketches](https://github.com/verfehlix/GeoTasks/wiki/UI-Sketches)

Ideen und Änderungsvorschläge etc. bitte einfach hier in dem Issue als Kommentar :smiley:

Danke!

**Comment by fabianstz** [comment]
Die Sketches finde ich haben ne sehr gute Struktur. Wenn das so umsetzbar ist, wäre super. Beschreibung, Ort, Radius und Fälligkeitsdatum deckt auch, wie schon besprochen, alles ab was wir brauchen. Das einzige was mir hier noch einfallen würde wären Tags. Also die Möglichkeit die Tasks manuell taggen zu können, einfach um eigene Kategorien (Bsp: Groceries, School, etc.) zu haben. Aber da ich nicht abschätzen kann wie aufwendig das zu Code ist, entscheidet ihr mal lieber ob wir das brauchen 😉 Good work Felix

**Comment by verfehlix** [comment]
Alles klar, danke fürs Feedback!
In wie weit wir das so umgesetzt bekommen sehen wir dann :grin:. 
Über so eine Art Kategorie bzw. Tags hab ich auch schon nachgedacht, je nach dem wie wir das umsetzen ist das viel / wenig Aufwand. 

Ich denke eine Methode, es ohne viel Aufwand zu implementieren wäre, den Nutzer den Tag selbst eintippen zu lassen. Dann wird er gemeinsam mit dem Task in der Datenbank abgelegt und beim nächsten "Task Erstellen" könnten wir ihm als Vorschläge die bisher verwendeten Tags bieten. Das ist dann relativ einfach umzusetzen ( @BlackIHawk  Datenbank-technisch einfach eine spalte "tag" mehr in der tasks tabelle und für die Vorschläge dann ein `SELECT DISTINCT tag FROM tasks ORDER BY timestamp DESC` oder sowas in die Richtung...). 
So eine extra Ansicht (Activity) um Tags zu anzulegen / zu löschen / Farben zuzuordnen etc. wäre bisschen luxoriöser (in etwa so wie bei GitHub Issues hier die Labels) aber eben auch viel mehr Aufwand. 
Was haltet ihr davon?
