### ISSUE TITLE
Task View

### ISSUE THREAD

**Issue by StefanHelmstetter** [verfehlix/GeoTasks#6]
Show properties of a single Task.

Usages:
- clicking on a task to show properties
- clicking on the notification opens the Task the notification belongs to
- clicking on a Task in the Map

**Comment by verfehlix** [comment]
**STATUS:**
- [X]    clicking on a task to show properties
- [x]   clicking on the notification opens the Task the notification belongs to
- [x]    clicking on a Task in the Map
